### ISSUE TITLE
[Feature Request] Support for Custom Fishing Loot from AuraSkills Plugin

### ISSUE THREAD

**Issue by reyes256** [Shershnyaga007/BetterCallFishing#4]
I'm currently trying **BetterCallFishing** and **AuraSkills** together for the first time, and i've noticed that this plugin overwrites the chance of getting 'rare' and 'epic' loot from the AuraSkills Fishing Skill Sources, if i modify the chances of getting epic loot to 100% of the time in the config file, the auraskills plugin rewards me with the xp and so, but it doesnt give the custom loot, it just spawns a fish like the BetterCallFishing plugin intended

### Expected Behavior
It would be beneficial if the BetterCallFishing plugin could allow or integrate the custom fishing loot items defined by the AuraSkills plugin. This way, players can enjoy the enhanced fishing experience with rare and epic items without losing the benefits provided by BetterCallFishing.

### Actual Behavior
Currently, BetterCallFishing restricts the fishing loot to only vanilla fish, preventing the custom loot from AuraSkills from being caught.

### Additional Context
- **AuraSkills Version**: 2.1.1
- **BetterCallFishing Version**: 2.0.1-b1
- **Minecraft Version**: 1.20.6
- **Server Type**: Paper #140
- **Other Plugins Installed**: Essentialsx

**Comment by Shershnyaga007** [comment]
Ok. I'll try to add the necessary dependencies.
If you want, I can send test versions with this function to you on discord.
My discord: shershnyaga

**Comment by Shershnyaga007** [comment]
https://github.com/Shershnyaga007/BetterCallFishing/releases/tag/v2.0.3-b6

Try this.

**Comment by Shershnyaga007** [comment]
https://www.spigotmc.org/resources/bettercallfishing.108426/
I make new release.

**Comment by reyes256** [comment]
Awesome work man!!!, i've just tested it and it works great, now i can get the custom loot from AuraSkill. Thank Youu!

**Comment by Shershnyaga007** [comment]
Thanks for report! I will be glad if you give 5 stars on SpigotMC)
