### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mikey1201** [Shershnyaga007/BetterCallFishing#7]
I like this plugin but catching pufferfish is frustrating for players because of the poison 4 effect. Could you add the ability to disable catching actual pufferfish to the config file?

**Comment by Shershnyaga007** [comment]
![2024-07-07_01-27-52](https://github.com/RubyHorizon/BetterCallFishing/assets/64916175/5d5792ca-5ac8-4456-b878-d1ac8b06f769)
Good idea! This feature will be added in the next update.
